---
title: "ec1207_HW1"
author: "Revanth"
date: "2024-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Q1. Ask an important question you want answered (1 at least)

a. Can we predict the sale price of residential properties in Texas based on their location, square footage, number of bedrooms, and amenities offered?

b. Is there any correlation between the age of the property(year built) and its sale price

c. Differences in sale prices between residential properties and commericial properties in Texas.

Q2. Answer why this question(s) is/are important to you?

This gives insights on various factors such as location, property size, amenities and bedroom count influence property prices. This helps in taking better informed decisions.
Also helps in understanding the relationships between dependent and independent variables, this helps in forecasting better prices.
These also gives us certain trends and patterns in the prices.

Q3. Find and collect data (need one dependent variable and more than 3 dependent variables)?

https://www.kaggle.com/datasets/kanchana1990/texas-real-estate-trends-2024-500-listings/data

Q4. Describe your data

Dependent variable:
a. Sale price
b. Days on market

Independent Variables
a. type
b. Location
c. sqft
d. beds
e. baths
f. status
g. year_built
h. sub_type

Data description

Sale price: Final sale price of the property
Days on market: Number of days the property is on sale in market

listing_id: unique id of the real estate listing
property_type: This indicates the type of the property
location: address of the property
sqft: Gives the sq.ft size of the property
beds: Number of beds in the property
baths: Number of bathrooms in the property
status: Current status of the listing
year_built: year in which the property is built
sub_type: sub category of the property type.


